packages:
  - apps/*
  - benchmarks
  - packages/*

autoInstallPeers: false
engineStrict: true
packageManagerStrict: true
preferFrozenLockfile: true
saveExact: true
sharedWorkspaceLockfile: true
strictPeerDependencies: true

allowBuilds:
  cpu-features: false
  esbuild: true
  protobufjs: false
  ssh2: false

overrides:
  cookie@<0.7.0: 0.7.2
